### ISSUE TITLE
Easy way to keep up to date?

### ISSUE THREAD

**Issue by LucidTaZ** [dcarbone/php-fhir-generated#4]
Hey, I'm about to clone this to generate updated classes following the recent generator fix(es) and to add a readme entry with instructions on how to do this, but I'd like to ask if you already have a tool lying around for this?

Things that I'd like clarification on:

- With default config the namespace becomes (e.g.) `HL7\FHIR\STU3`, while the files in this repo are in namespace `PHPFHIRGenerated`. Why not keep the original (versioned) namespace?
- Also, do you have a custom config.php lying around for that or do you use some CLI argument?
- Each FHIR version has a different branch, do you have ideas on managing differences between branches?
- Do you have a script to generate and commit updates easily? And where should it be in the repository, if anywhere?

It would be nice if you could provide info on this so that any contributor/forker can generate new files using the same process that you use so far. That way you don't have to do a lot of extra work when someone needs updated classes.

**Comment by dcarbone** [comment]
1. This repo was added before the contributor-added generate script, and I don't really have a strong opinion on the namespaces.  I figure if somebody wants something different they'll just create a config.
1. The `master` branch in the generated repo is based off of output from the `master` branch of the generator, however the DSTU1/DSTU2/STU3 branches are based off of the latest released version of the generator.  The generate script is only present in the `master` branch of the generator as I've not felt the work in master is sufficient for a release yet.
1. There will be no diff management between branches.  They are wholly independent entities built off of different versions of the spec. The differences are not significant.
1. No, the generated repo was merely intended as a convenience to those who did not want to generate the files themselves.  Right now with how infrequently updates are pushed I just switch branches and re-run the generator.

I suppose one REALLY cool thing would be to integrate travis into the generator lib that would automatically push new versions to each of the generated branches.  That would severely reduce the manual labor.  It would have to limit commits to the named branches to only tag releases.

**Comment by LucidTaZ** [comment]
Thanks for the reply, it clears things up.

I've been playing around a bit and have these insights:

1. My question was specifically for the files in this repository, since I think it's a really useful thing - next to the generator - to have a composer-usable FHIR library. But your response clarifies enough.
2. _(No comments)_
3. One reason I could think of to share certain parts of code is for tests. In between specs I guess most tests should stay valid, and if there are differences then diffing the expected outputs of tests should point out how the specs differ. I've set up a simple test suite in the STU3 branch right now using phpunit. (Note to self: Think about a simpler approach with `.phpt` files, since they do a great job in simply showing inputs and expected outputs and don't pull in dependencies.)
4. Our use case for a generate repo is to have a proper dependency workflow: all our dependencies are composer libraries except for the generated FHIR classes. This leads to subtle exceptions in ignore files, enormous diffs and that sort of problems. So I guess one could call it a convenience but I think it's a quite common one.
5. The fully automated solution would really rock and alleviates the need for a contributor guideline on how to keep this repo up to date. I'll let the option sink in and maybe work on a PR.

Lastly, thank you for taking the time to comment on this and maintaining the repos!

**Comment by dcarbone** [comment]
Hmm, what are you running into when trying to use the generated repo as a dependency?  Part of the generation is to provide a composer.json file to use for that specific purpose.  It is registered with Packagist here: https://packagist.org/packages/dcarbone/php-fhir-generated.

To point 3:  I think the test cases should be attached to the generator itself, not the generated code.  The point of this repo is to contain wholly-generated code, not code I have to futz around with and merge and etc. To that end, the generator must be the one doing ALL of the writing.  The generated repo cannot have non-generated code in it, and I will not accept any PR doing so.  This would also continue to support the original intent of the generator, which was to enable you to create your own generated version that gets stored in some internal composer mirror (as I did with Satis when I was actively using FHIR).

I can definitely see the potential of having a test suite being created as part of the generation.  Since I assume you are actively using STU3, if you would like to create a PR against the generator itself that creates a version-specific test suite implementation as part of the generation that would be amazing.

And again, apologies for the slow progress on this lib.  Other things keep taking priority.

**Comment by LucidTaZ** [comment]
There's no issue in using this repository as a Composer library, I was clarifying our use case.

I don't really believe in generated tests, because it's just more code that's just as complex as the original code. In my opinion tests should be simple to read and understand so that anyone can verify their validity.

**Comment by dcarbone** [comment]
The output of the test generation should be the same as if placed directly into one of these branches.  The “generation” part should be fairly static, and could be something as simple as copying a predefined dir of tests to the output.

Trying to maintain a common test suite between all of these branches while maintaining the necessary differences would be a pain if committed directly to this repo. It would also prevent others who generate their own from benefiting from them. 

I could also foresee it being a separate repository just for tests that are set as a dev dependency in the output.

I don’t mean to discourage your input, I appreciate your ideas and would like to see them come to fruition. I just want the purposes of each repo to be maintained.
